name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "pyproject.toml"

permissions:
  issues: write

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'rookiestar28' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install comfy-cli
        run: pip install comfy-cli
      - name: Publish Custom Node
        env:
          REGISTRY_ACCESS_TOKEN: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
        run: comfy --skip-prompt --no-enable-telemetry env comfy node publish --token "${REGISTRY_ACCESS_TOKEN}"
